import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Desktopnav from "./ui/navs/desktopnav";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="body">

       
        <div className="flex h-screen">
          {/* Fixed Side Navigation */}
          <div className="flex-none hidden md:block">
            <Desktopnav />
          </div>
          {/* Scrollable Content Container */}
          <main className=" p-4">
            {children}
          </main>
        </div>
        </div>
      </body>
    </html>
  );
}
